name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:

  linux-tests:

    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --prefer-stable

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
      
  macos-tests:
    
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1']
        
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --prefer-stable

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
        
  windows-tests:
    
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '8.1']

    runs-on: windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --prefer-stable

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
